version: "3"

services:
  frontend:
    container_name: hubit_frontend
    build: frontend/
    ports:
      - 4200:4200
    volumes:
      - ./frontend/src:/usr/frontend/src
      - ./frontend/tests:/usr/frontend/tests
      - ./frontend/test:/usr/frontend/test

  backend:
    container_name: hubit_backend
    build: backend/
    ports:
    - 3000:3000
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - database
    volumes:
      - ./backend/src:/usr/backend/src
      - ./backend/tests:/usr/backend/tests
      - ./backend/coverage:/usr/backend/coverage

  database:
    container_name: hubit_mongo
    image: mongo:6.0
    ports:
    - 27017:27017
    volumes:
    - ./database/data:/data/db

  proxy:
    container_name: hubit_apache
    build: proxy/
    ports:
     - 8080:80
    depends_on:
      - frontend
      - backend

  backend_tests:
    container_name: hubit_backend_test
    build: backend/
    command: npm run test
    volumes:
      - ./backend/src:/usr/backend/src
      - ./backend/tests:/usr/backend/tests
      - ./backend/coverage:/usr/backend/coverage
   