version: "3"

services:
  backend:
    container_name: hubit_backend
    build: backend/
    ports:
    - 3000:3000
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - database

  database:
    container_name: hubit_mongo
    image: mongo:6.0
    ports:
    - 27017:27017
    volumes:
    - ./database/data:/data/db

  backend_tests:
    container_name: hubit_backend_test
    build: backend/
    command: npm run test


